[package]
name = "wglobe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bytemuck = "1.23.2"
egui = "0.32.1"
env_logger = "0.11.8"
log = "0.4.27"
pollster = "0.4.0"
wgpu = "26.0.1"
winit = "0.30.12"
